# Generated by Django 5.1.3 on 2024-11-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailMessage',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='content',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='tempemail',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
