# Generated by Django 5.1.3 on 2024-11-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_rename_emailmessage_email_rename_content_email_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempemail',
            name='address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('temp_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailmessages', to='emailapp.tempemail')),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
